declare module 'grapesjs';
declare module 'grapesjs-preset-webpage';
declare module 'grapesjs-blocks-basic';
declare module 'grapesjs-plugin-forms';
declare module 'grapesjs-plugin-export';
declare module 'grapesjs-component-countdown';
declare module 'grapesjs-navbar';
declare module 'grapesjs-style-bg';
declare module 'grapesjs-tabs';
declare module 'grapesjs-tooltip';
declare module 'grapesjs-custom-code';
declare module 'grapesjs-touch';
declare module 'grapesjs-parser-postcss';
declare module 'grapesjs-plugin-ckeditor';
// declare module 'grapesjs-templates';
// declare module 'grapesjs-project-manager';
// declare module 'grapesjs-template-manager';
// declare module 'grapesjs-swiper-slider';
// declare module 'grapesjs-blocks-bootstrap4';
// declare module 'grapesjs-lory-slider';
// declare module 'grapesjs-plugin-filestack';